windowrulev2 = opacity 0.80,class:^(Alacritty)$
windowrulev2 = opacity 0.80,class:^(kitty)$
windowrulev2 = opacity 0.80,class:^(thunar)$
windowrulev2 = opacity 0.80,class:^(obsidian)$
windowrulev2 = opacity 0.80,class:^(Spotify)$
windowrulev2 = opacity 0.80,class:^(discord)$
windowrulev2 = opacity 0.80,class:^(vesktop)$
windowrulev2 = opacity 0.80,class:^(org.telegram.desktop)$
windowrulev2 = opacity 0.80,class:^(com.ayugram.desktop)$
windowrulev2 = opacity 0.80,class:^(steam)$
windowrulev2 = opacity 0.80,class:^(Rofi)$
windowrulev2 = opacity 0.80,class:^(better_control.py)$
